### ISSUE TITLE
Remove allowed quantity after spending or when setting to zero

### ISSUE THREAD

**Issue by JrSchild** [Interblockchain/BasicContract#1]
Hi there,

I noticed that you modified the contract to have the account removed when there are no tokens left. However, the allowed quantity record will remain after it is set to zero.

Maybe you want to consider removing it after it is spent, and also allow setting it to zero to remove it.

**Comment by pboulanger5** [comment]
Good point. Users should be capable of deleting their allowances and freeing up space. Deleting when it reaches zero seems like a good default behaviour.
I will make the modifications.

Thanks for doing our first issue!
